### ISSUE TITLE
USD entry appears to be out of sync with the community spreadsheet.

### ISSUE THREAD

**Issue by comand** [koaleksa/vfxpy#1]
Thanks for putting this together! I noticed that the entry for USD is out of date with respect to the community sheet, which states that USD has Python 3 support as of the 20.05 (May 2020) release. Can you please arrange to update this entry in your copy of the data? Thanks in advance.

**Comment by alxkocic** [comment]
Thanks for pointing that out Cory. Site has been updated. Closing the issue. Cheers 👍

**Comment by comand** [comment]
Thanks!
